### ISSUE TITLE
mupen64plus segfaults on MALI

### ISSUE THREAD

**Issue by Kivutar** [libretro/Lakka#153]
With gln64, rice or angrylion gfx_plugin

    Program received signal SIGSEGV, Segmentation fault.
    0xb6d4a59e in _essl_mali200_write_instructions () from /usr/lib/libEGL.so
    (gdb) bt
    #0  0xb6d4a59e in _essl_mali200_write_instructions () from /usr/lib/libEGL.so
    #1  0xb6d567f2 in schedule () from /usr/lib/libEGL.so
    #2  0xb6d57a54 in _essl_mali200_schedule_single_operation () from /usr/lib/libEGL.so
    #3  0xb6d584f8 in _essl_mali200_schedule_function () from /usr/lib/libEGL.so
    #4  0xb6d49c72 in _essl_mali200_driver () from /usr/lib/libEGL.so
    #5  0xb6d3e474 in _essl_run_compiler () from /usr/lib/libEGL.so
    #6  0xb6d2043e in __mali_compile_essl_shader () from /usr/lib/libEGL.so
    #7  0xb6d138bc in _gles2_compile_shader () from /usr/lib/libEGL.so
    #8  0xb6d0f512 in glCompileShader () from /usr/lib/libEGL.so
    Cannot access memory at address 0x3
    #9  0xb00a8840 in ?? () from /usr/lib/libretro/mupen64plus_libretro.so
    Cannot access memory at address 0x3
    Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by Kivutar** [comment]
Possible fix https://github.com/libretro/mupen64plus-libretro/issues/101

**Comment by Kivutar** [comment]
Fixed.
